class_name RemakeText
extends RefCounted
## Translations of the remake's own texts (options, co-op screen, setup,
## messages) — texts.res has none of them. The original has no language
## choice: the language follows the edition supplied (`detect`, run by
## GameData._open_text_archives): code page 1251 → Russian, the German
## texts.res (umlauts) → German, else English. Before any game data is open
## (the first-run setup screen) the system locale picks among the three.
## Keys are the English texts; a missing one stays English. Format arguments
## are filled in by the caller after `t`.

static var lang := _os_lang()


static func _os_lang() -> String:
	var l := OS.get_locale_language()
	return l if l in ["ru", "de"] else "en"


## The edition's language from its texts.res (EIText.code_page already set):
## English and German are both Windows-1252; the English "string" entries have
## no ä ö ü ß Ä Ö Ü at all, the German ones thousands.
static func detect(texts: EIResArchive) -> String:
	if texts == null:
		return _os_lang()
	if EIText.code_page == 1251:
		return "ru"
	var umlauts := 0
	for n: String in texts.entries:
		if not n.begins_with("string "):
			continue
		for b in texts.read(n):
			if b in [0xc4, 0xd6, 0xdc, 0xe4, 0xf6, 0xfc, 0xdf]:
				umlauts += 1
	return "de" if umlauts >= 50 else "en"


## The text `en` in the edition's language.
static func t(en: String) -> String:
	if lang == "en":
		return en
	var tr: Array = TEXTS.get(en, [])
	var i := 0 if lang == "ru" else 1
	return String(tr[i]) if tr.size() > i and String(tr[i]) != "" else en


## `t` of each element (e.g. a [label, tip] pair).
static func tl(list: Array) -> Array:
	return list.map(func(s): return t(String(s)))


## English → [Russian, German].
const TEXTS := {
	"lighting and surfaces": ["свет и поверхности", "Licht und Oberflächen"],
	"Lighting and surfaces…": ["Свет и поверхности…", "Licht und Oberflächen…"],
	"Dynamic firelight, surface materials, leaf backlighting, rain on surfaces and lava lighting.": ["Динамический свет огня, материалы, свет сквозь листву, мокрые поверхности и свет лавы.", "Dynamisches Feuerlicht, Oberflächenmaterialien, durchscheinende Blätter, nasse Oberflächen und Lavalicht."],
	"Dynamic firelight": ["Динамический свет огня", "Dynamisches Feuerlicht"],
	"Warm, flickering torches and fire; spell lights brighten nearby surfaces and fade out softly. Nearby fire and lava lights share a limited number of shadows.": ["Тёплый мерцающий свет факелов и огня; свет заклинаний освещает поверхности и плавно гаснет. Ближайшие огни и лава используют ограниченное число теней.", "Warmes, flackerndes Fackel- und Feuerlicht; Zauber beleuchten nahe Oberflächen und klingen sanft ab. Nahe Feuer- und Lavalichter teilen sich eine begrenzte Zahl von Schatten."],
	"Surface materials": ["Материалы поверхностей", "Oberflächenmaterialien"],
	"Metal equipment catches the light; wood and stone have subtle surface relief. Uses the original textures and equipment materials.": ["Металлическое снаряжение отражает свет; дерево и камень получают лёгкий рельеф. Используются исходные текстуры и материалы снаряжения.", "Metallausrüstung reflektiert Licht; Holz und Stein erhalten ein dezentes Relief. Verwendet die Originaltexturen und Ausrüstungsmaterialien."],
	"Leaf backlighting": ["Свет сквозь листву", "Durchscheinende Blätter"],
	"Sunlight shines softly through leaves while trunks remain solid.": ["Солнечный свет мягко просвечивает сквозь листья; стволы остаются непрозрачными.", "Sonnenlicht scheint sanft durch Blätter; Stämme bleiben lichtundurchlässig."],
	"Rain on surfaces": ["Дождь на поверхностях", "Regen auf Oberflächen"],
	"Rain gradually darkens exposed ground and adds wet highlights and water ripples. Surfaces dry after the rain; caves, snow and lava stay unchanged.": ["Дождь постепенно затемняет открытый грунт, добавляет влажный блеск и круги на воде. После дождя поверхности высыхают; пещеры, снег и лава не меняются.", "Regen dunkelt ungeschützten Boden allmählich ab und erzeugt nassen Glanz und Wasserringe. Danach trocknen Oberflächen; Höhlen, Schnee und Lava bleiben unverändert."],
	"Lava lighting": ["Свет лавы", "Lavalicht"],
	"Lava casts a warm glow onto nearby banks, buildings and creatures. A limited number of nearby lights follows the view.": ["Лава освещает тёплым светом ближайшие берега, постройки и существ. Ограниченное число источников света следует за камерой.", "Lava wirft einen warmen Schein auf nahe Ufer, Gebäude und Kreaturen. Eine begrenzte Zahl naher Lichter folgt der Kamera."],
	"Switches every remake graphics effect off, leaving the original 2000 look (confirm with ✓).": ["Отключает все графические эффекты ремейка, возвращая вид оригинала 2000 года (подтвердите ✓).", "Schaltet alle Grafikeffekte des Remakes aus und stellt den Look von 2000 wieder her (mit ✓ bestätigen)."],
	# --- Options: the remake's own rows (GameData.REMAKE_OPTIONS, DISPLAY_CHOICES) ---
	"On": ["Вкл.", "An"],
	"Off": ["Выкл.", "Aus"],
	"Windowed": ["В окне", "Fenster"],
	"Fullscreen": ["Полный экран", "Vollbild"],
	"Borderless fullscreen": ["Окно без рамки", "Randloses Vollbild"],
	"Display refresh": ["Частота монитора", "Bildwiederholrate"],
	"Adaptive": ["Адаптивная", "Adaptiv"],
	"Original": ["Оригинальная", "Original"],
	"Modern": ["Современная", "Modern"],
	"Low": ["Низкое", "Niedrig"],
	"Medium": ["Среднее", "Mittel"],
	"High": ["Высокое", "Hoch"],
	"Ultra": ["Ультра", "Ultra"],
	"Light": ["Слабое", "Leicht"],
	"Normal": ["Обычное", "Normal"],
	"Strong": ["Сильное", "Stark"],
	"Native (%d × %d)": ["Родное (%d × %d)", "Nativ (%d × %d)"],
	"remake": ["ремейк", "Remake"],
	"remake effects": ["эффекты ремейка", "Remake-Effekte"],
	"HD textures": ["HD-текстуры", "HD-Texturen"],
	"The original ground and object textures upscaled 2x once at load (edge-preserving Lanczos on the GPU): sharper up close, same colours. Applies from the next zone load.": ["Оригинальные текстуры земли и объектов при загрузке увеличиваются вдвое (Lanczos на видеокарте с сохранением краёв): чётче вблизи, цвета те же. Действует со следующей загрузки зоны.", "Die originalen Boden- und Objekttexturen werden beim Laden einmal auf das Doppelte hochskaliert (kantenerhaltendes Lanczos auf der GPU): schärfer aus der Nähe, gleiche Farben. Wirkt ab dem nächsten Laden einer Zone."],
	"Soft particles": ["Мягкие частицы", "Weiche Partikel"],
	"Smoke, fire and magic fade softly where they meet the ground and walls instead of cutting through them with a hard line.": ["Дым, огонь и магия мягко тают у земли и стен, а не обрезаются о них резкой линией.", "Rauch, Feuer und Magie laufen an Boden und Wänden weich aus, statt sie mit einer harten Linie zu schneiden."],
	"Lit smoke and dust": ["Освещённые дым и пыль", "Beleuchteter Rauch und Staub"],
	"Smoke, dust and blood take the scene's light: unchanged in daylight, darker at night and in caves instead of glowing.": ["Дым, пыль и кровь освещаются светом сцены: днём как прежде, ночью и в пещерах темнее, а не светятся.", "Rauch, Staub und Blut nehmen das Licht der Szene an: bei Tag unverändert, nachts und in Höhlen dunkler, statt zu leuchten."],
	"Contact shadows": ["Контактные тени", "Kontaktschatten"],
	"A soft shadow on the ground under every creature, so figures sit on the ground also in shade, at night and in caves.": ["Мягкая тень на земле под каждым существом, чтобы фигуры стояли на земле и в тени, ночью и в пещерах.", "Ein weicher Schatten unter jedem Wesen, damit die Figuren auch im Schatten, nachts und in Höhlen auf dem Boden stehen."],
	"Anti-aliasing": ["Сглаживание", "Kantenglättung"],
	"Smooths jagged edges. MSAA 4× + SMAA: sharpest (default). TAA and FSR 2 smooth foliage and thin lines best but soften textures slightly and can ghost on fast motion. FSR 2 also upscales when Render scale is below 100 %.": ["Сглаживает зубчатые края. MSAA 4× + SMAA: самое чёткое (по умолчанию). TAA и FSR 2 лучше сглаживают листву и тонкие линии, но слегка размывают текстуры и могут оставлять шлейф при быстром движении. FSR 2 также масштабирует изображение, если масштаб рендера ниже 100 %.", "Glättet gezackte Kanten. MSAA 4× + SMAA: am schärfsten (Standard). TAA und FSR 2 glätten Laub und dünne Linien am besten, machen Texturen aber etwas weicher und können bei schnellen Bewegungen nachziehen. FSR 2 skaliert außerdem hoch, wenn die Renderskalierung unter 100 % liegt."],
	"Shadow quality": ["Качество теней", "Schattenqualität"],
	"Softness and resolution of sun and torch shadows (Ultra: widest soft filter, largest shadow maps).": ["Мягкость и разрешение теней от солнца и факелов (Ультра: самый широкий фильтр, самые большие карты теней).", "Weichheit und Auflösung der Sonnen- und Fackelschatten (Ultra: breitester Weichzeichner, größte Schattenkarten)."],
	"Shadows fitted to the view": ["Тени по области обзора", "Schatten an die Sicht angepasst"],
	"The sun's shadow cascades span only the visible distance and the zone's size, so near shadows get sharper; off: a fixed 220 m.": ["Каскады солнечных теней охватывают только видимое расстояние и размер зоны, поэтому ближние тени чётче; выкл.: всегда 220 м.", "Die Schattenkaskaden der Sonne decken nur die sichtbare Entfernung und die Größe der Zone ab, nahe Schatten werden schärfer; aus: fest 220 m."],
	"Texture filtering": ["Фильтрация текстур", "Texturfilterung"],
	"Anisotropic filtering: ground textures stay sharp at grazing angles.": ["Анизотропная фильтрация: текстуры земли остаются чёткими под острым углом.", "Anisotrope Filterung: Bodentexturen bleiben auch bei flachem Blickwinkel scharf."],
	"Torch and fire glow": ["Свечение факелов и огня", "Leuchten von Fackeln und Feuer"],
	"Torches, camp fires and spell lights glow in the night mist (needs Volumetric fog).": ["Факелы, костры и свет заклинаний светятся в ночной дымке (нужен объёмный туман).", "Fackeln, Lagerfeuer und Zauberlicht leuchten im nächtlichen Dunst (benötigt Volumetrischen Nebel)."],
	"Atmospheric sky": ["Атмосферное небо", "Atmosphärischer Himmel"],
	"Sun disc, moon and stars at night over the original sky dome, and the open top of the dome faded into the sky colour; off: the original dome only.": ["Солнечный диск, ночью луна и звёзды поверх оригинального купола неба, открытая верхушка купола переходит в цвет неба; выкл.: только оригинальный купол.", "Sonnenscheibe, nachts Mond und Sterne über der originalen Himmelskuppel, deren offene Spitze in die Himmelsfarbe übergeht; aus: nur die originale Kuppel."],
	"Water and lava effects": ["Эффекты воды и лавы", "Wasser- und Lavaeffekte"],
	"Animated ripples, refraction, depth colour and sun glints; breaking surf on sea coasts, calmer rivers and bogs; glowing, churning lava. Off: the plain blended water.": ["Рябь, преломление, цвет глубины и солнечные блики; прибой у морских берегов, спокойная вода рек и болот; светящаяся бурлящая лава. Выкл.: простая полупрозрачная вода.", "Bewegte Wellen, Brechung, Tiefenfarbe und Sonnenglitzern; Brandung an Meeresküsten, ruhigeres Wasser in Flüssen und Sümpfen; glühende, brodelnde Lava. Aus: einfaches überblendetes Wasser."],
	"Water reflections (SSR)": ["Отражения на воде (SSR)", "Wasserspiegelungen (SSR)"],
	"Natural": ["Естественные", "Natürlich"],
	"Mirror": ["Зеркальные", "Spiegelnd"],
	"Natural: subtle, rippled reflections. Mirror: stronger, sharper scenery with gentler distortion (default). Off keeps sky reflections. Needs Water and lava effects. Off-screen and transparent objects may be absent; Mirror costs more GPU time.": ["Естественные: мягкие отражения с рябью. Зеркальные: более чёткие и яркие отражения с меньшими искажениями (по умолчанию). Выкл.: остаётся отражение неба. Требует эффектов воды и лавы. Объекты вне экрана и прозрачные объекты могут не отражаться; зеркальный режим сильнее нагружает видеокарту.", "Natürlich: dezente Spiegelungen mit Wellen. Spiegelnd: kräftigere, schärfere Umgebung mit sanfterer Verzerrung (Standard). Aus behält Himmelsspiegelungen. Benötigt Wasser- und Lavaeffekte. Objekte außerhalb des Bildes und transparente Objekte können fehlen; Spiegelnd benötigt mehr GPU-Zeit."],
	"Wind in foliage": ["Ветер в листве", "Wind im Laub"],
	"Trees and bushes sway in the wind.": ["Деревья и кусты качаются на ветру.", "Bäume und Büsche wiegen sich im Wind."],
	"Volumetric fog / light shafts": ["Объёмный туман / лучи света", "Volumetrischer Nebel / Lichtstrahlen"],
	"Light mist lit by the sun (shafts through the trees at dawn and dusk) and the torches.": ["Лёгкая дымка, освещённая солнцем (лучи сквозь деревья на рассвете и закате) и факелами.", "Leichter Dunst, von der Sonne (Strahlen durch die Bäume bei Morgen- und Abenddämmerung) und den Fackeln beleuchtet."],
	"Terrain detail": ["Детализация земли", "Geländedetails"],
	"Sharper original ground textures with fewer tile seams; relief follows painted rock and path patterns, with softer sand and snow, fine grass and damp banks.": ["Более чёткие исходные текстуры земли с менее заметными стыками; рельеф повторяет рисунок камней и дорожек, песок и снег мягче, трава мельче, берега влажные.", "Schärfere Original-Bodentexturen mit weniger sichtbaren Kachelnähten; das Relief folgt den gemalten Fels- und Wegmustern, mit weicherem Sand und Schnee, feinem Gras und feuchten Ufern."],
	"Heat haze": ["Марево", "Hitzeflimmern"],
	"Air shimmering above torches and camp fires.": ["Дрожание воздуха над факелами и кострами.", "Flimmernde Luft über Fackeln und Lagerfeuern."],
	"Ambient occlusion": ["Затенение окружения", "Umgebungsverdeckung"],
	"Soft contact shadows (SSAO).": ["Мягкие контактные тени (SSAO).", "Weiche Kontaktschatten (SSAO)."],
	"Bloom": ["Ореолы", "Bloom"],
	"Glow around bright lights.": ["Свечение вокруг ярких источников света.", "Leuchten um helle Lichter."],
	"Map edge fade": ["Растворение края карты", "Kartenrand ausblenden"],
	"The last few metres of land at the map edge fade into the sky colour instead of ending in a hard edge.": ["Последние метры земли у края карты растворяются в цвете неба, а не обрываются резко.", "Die letzten Meter Land am Kartenrand gehen in die Himmelsfarbe über, statt hart zu enden."],
	"Display mode": ["Режим экрана", "Anzeigemodus"],
	"Windowed, fullscreen, or a borderless window covering the screen.": ["В окне, на полный экран или окно без рамки во весь экран.", "Fenster, Vollbild oder ein randloses Fenster über den ganzen Bildschirm."],
	"Resolution": ["Разрешение", "Auflösung"],
	"Window size when windowed; in fullscreen the 3D view is rendered at this size and scaled to the screen (the interface stays sharp).": ["Размер окна в оконном режиме; на полном экране 3D-изображение строится в этом размере и растягивается на экран (интерфейс остаётся чётким).", "Fenstergröße im Fenstermodus; im Vollbild wird die 3D-Ansicht in dieser Größe berechnet und auf den Bildschirm skaliert (die Oberfläche bleibt scharf)."],
	"Frame rate limit": ["Ограничение кадров", "Bildratenbegrenzung"],
	"Highest frames per second; Display refresh = the monitor's refresh rate.": ["Наибольшее число кадров в секунду; «Частота монитора» = частота обновления монитора.", "Höchste Bilder pro Sekunde; Bildwiederholrate = die des Monitors."],
	"VSync": ["Вертикальная синхронизация", "VSync"],
	"Wait for the monitor's refresh (no tearing); adaptive tears only when a frame is late.": ["Ждать обновления монитора (без разрывов); адаптивная допускает разрыв только при опоздании кадра.", "Auf den Bildaufbau des Monitors warten (kein Tearing); adaptiv reißt nur, wenn ein Bild zu spät kommt."],
	"Show FPS": ["Показывать FPS", "FPS anzeigen"],
	"A frames-per-second counter in the top right corner.": ["Счётчик кадров в секунду в правом верхнем углу.", "Ein Zähler der Bilder pro Sekunde oben rechts."],
	"Keep mouse in window": ["Мышь не покидает окно", "Maus im Fenster halten"],
	"The pointer cannot leave the game window (e.g. onto a second monitor) while the game has focus; it is free again when you switch away.": ["Курсор не может покинуть окно игры (например, уйти на второй монитор), пока игра активна; при переключении в другое окно он снова свободен.", "Der Mauszeiger kann das Spielfenster (z. B. zu einem zweiten Monitor) nicht verlassen, solange das Spiel aktiv ist; nach dem Wechsel in ein anderes Fenster ist er wieder frei."],
	"Render scale": ["Масштаб рендера", "Renderskalierung"],
	"Smooth motion": ["Плавное движение", "Flüssige Bewegung"],
	"Creatures are drawn between the game's 60 steps a second, so they move smoothly on screens faster than 60 Hz. Visual only.": ["Существа рисуются между 60 шагами игры в секунду и движутся плавно на экранах с частотой выше 60 Гц. Влияет только на изображение.", "Kreaturen werden zwischen den 60 Spielschritten pro Sekunde gezeichnet und bewegen sich auf Bildschirmen über 60 Hz flüssig. Nur optisch."],
	"Resolution of the 3D view relative to the window: below 100 % faster, above it sharper (supersampling).": ["Разрешение 3D-изображения относительно окна: ниже 100 % быстрее, выше — чётче (суперсэмплинг).", "Auflösung der 3D-Ansicht relativ zum Fenster: unter 100 % schneller, darüber schärfer (Supersampling)."],
	"Far view": ["Дальний обзор", "Weitsicht"],
	"See 260 m instead of 100 m, with a long soft fade into the fog; off: the original 100 m view with its short fog band.": ["Видно на 260 м вместо 100 м, с долгим мягким переходом в туман; выкл.: оригинальные 100 м с короткой полосой тумана.", "260 m statt 100 m Sicht mit einem langen weichen Übergang in den Nebel; aus: die originalen 100 m mit dem kurzen Nebelband."],
	"Camera style": ["Тип камеры", "Kamerastil"],
	"Original: the 2000 game's camera. Modern: responsive pan, smooth zoom and terrain clearance. Middle drag turns; Alt + middle drag or right drag tilts; Shift + middle drag pans. Home centres; optional hero follow and see-through objects.": ["Оригинальная: камера игры 2000 года. Современная: отзывчивый сдвиг, плавное приближение и обход рельефа. Средняя кнопка поворачивает; Alt + средняя или правая меняет наклон; Shift + средняя сдвигает. Home центрирует; слежение и прозрачность включаются отдельно.", "Original: die Kamera des Spiels von 2000. Modern: direktes Verschieben, weiches Zoomen und Bodenabstand. Mittlere Taste dreht; Alt + mittlere oder rechte Taste neigt; Umschalt + mittlere verschiebt. Pos1 zentriert; Folgen und Transparenz sind optional."],
	"Camera pan speed (modern)": ["Скорость сдвига камеры (совр.)", "Kamera-Verschiebetempo (modern)"],
	"Speed of the modern camera's panning (keys, screen edges).": ["Скорость сдвига современной камеры (клавиши, края экрана).", "Tempo, mit dem die moderne Kamera verschoben wird (Tasten, Bildschirmränder)."],
	"Camera turn speed (modern)": ["Скорость поворота камеры (совр.)", "Kamera-Drehtempo (modern)"],
	"Speed of the modern camera's turning and tilting (drag, keys).": ["Скорость поворота и наклона современной камеры (мышь, клавиши).", "Tempo, mit dem sich die moderne Kamera dreht und neigt (Ziehen, Tasten)."],
	"Camera zoom speed (modern)": ["Скорость приближения (совр.)", "Kamera-Zoomtempo (modern)"],
	"Speed of the modern camera's zoom (wheel, keys).": ["Скорость приближения современной камеры (колесо, клавиши).", "Zoomtempo der modernen Kamera (Mausrad, Tasten)."],
	"Camera follows the hero": ["Камера следит за героем", "Kamera folgt dem Helden"],
	"Modern camera: follows the selected hero until you pan away. Home, F1-F3 or a portrait double-click centres and resumes following. Moving a hero never pulls the camera back. Off: these controls centre without following.": ["Современная камера: следит за выбранным героем, пока вы не отведёте её. Home, F1-F3 или двойной щелчок по портрету возвращают камеру и слежение. Движение героя не возвращает камеру. Выкл.: только центрирование, без слежения.", "Moderne Kamera: folgt dem gewählten Helden, bis du sie wegbewegst. Pos1, F1-F3 oder ein Doppelklick aufs Porträt zentriert und folgt wieder. Eine Bewegung des Helden holt sie nie zurück. Aus: nur zentrieren, ohne Folgen."],
	"See-through objects": ["Прозрачные объекты", "Durchsichtige Objekte"],
	"Modern camera: trees, houses and rocks that hide your heroes fade to see-through.": ["Современная камера: деревья, дома и скалы, заслоняющие ваших героев, становятся прозрачными.", "Moderne Kamera: Bäume, Häuser und Felsen, die deine Helden verdecken, werden durchsichtig."],
	"Show the move path through objects": ["Путь движения сквозь объекты", "Bewegungspfad durch Objekte"],
	"The dots of a move path and the ring at its target stay visible under water, under arches and behind rocks and walls, faded where something covers them. Off: as the original, which hides them there.": ["Точки пути движения и кольцо у цели видны под водой, под арками, за камнями и стенами; там, где их что-то закрывает, они бледнее. Выкл.: как в оригинале, где они там скрыты.", "Die Punkte des Bewegungspfads und der Ring am Ziel bleiben unter Wasser, unter Bögen und hinter Felsen und Mauern sichtbar, abgeschwächt, wo etwas sie verdeckt. Aus: wie im Original, das sie dort verbirgt."],
	"Full experience for companions": ["Полный опыт спутникам", "Volle Erfahrung für Gefährten"],
	"Single player: your hero and every companion (hired mercenaries such as Khador) each get the whole experience of a kill or quest. Off: as the original, which splits it equally among the living party.": ["Одиночная игра: ваш герой и каждый спутник (нанятые наемники, например Хадор) получают весь опыт за убийство или задание. Выкл.: как в оригинале, опыт делится поровну между живыми членами отряда.", "Einzelspiel: dein Held und jeder Gefährte (angeheuerte Söldner wie Khador) erhalten jeweils die volle Erfahrung für einen Sieg oder eine Aufgabe. Aus: wie im Original, aufgeteilt zu gleichen Teilen unter der lebenden Gruppe."],
	"Fog of war (single player)": ["Туман войны (одиночная игра)", "Nebel des Krieges (Einzelspiel)"],
	"Enemies and other people are only seen within reach of your party's eyes: 2 × the larger of sight and life sense + 5 m around each party member, as the original's network game does. Off: the original single player, everyone on the map is drawn.": ["Враги и другие персонажи видны только в пределах зрения вашего отряда: 2 × большее из зрения и чувства жизни + 5 м вокруг каждого члена отряда, как в сетевой игре оригинала. Выкл.: как в оригинальной одиночной игре, видны все на карте.", "Gegner und andere Personen sind nur in Sichtweite deiner Gruppe zu sehen: 2 × der größere Wert aus Sicht und Lebenssinn + 5 m um jedes Gruppenmitglied, wie im Netzwerkspiel des Originals. Aus: wie im originalen Einzelspiel, alle auf der Karte sind zu sehen."],
	"Full experience for every party member": ["Полный опыт каждому в команде", "Volle Erfahrung für jeden"],
	"Co-op host: every player's hero and every mercenary gets the whole experience of a kill or quest. Off: the original network rule (shared among the players' heroes by experience, mercenaries get none). Single player is not affected.": ["Для сервера сетевой игры: герой каждого игрока и каждый наемник получают весь опыт за убийство или задание. Выкл.: правило оригинальной сетевой игры (опыт делится между героями игроков по их опыту, наемники не получают ничего). На одиночную игру не влияет.", "Für den Server im Netzwerkspiel: der Held jedes Spielers und jeder Söldner erhält die volle Erfahrung für einen Sieg oder eine Aufgabe. Aus: die originale Netzwerkregel (aufgeteilt unter den Helden der Spieler nach Erfahrung, Söldner erhalten nichts). Das Einzelspiel ist nicht betroffen."],
	"Scale monsters to player count": ["Монстры сильнее с числом игроков", "Monster nach Spielerzahl"],
	"Co-op host: monsters get more health and hit harder for each player beyond the first (Light +25 % health / +12.5 % damage, Normal +50 % / +25 %, Strong +100 % / +50 % per extra player). Off: as the original.": ["Для сервера сетевой игры: за каждого игрока сверх первого монстры получают больше здоровья и бьют сильнее (Слабое +25 % здоровья / +12,5 % урона, Обычное +50 % / +25 %, Сильное +100 % / +50 % за каждого игрока). Выкл.: как в оригинале.", "Für den Server im Netzwerkspiel: Monster erhalten für jeden Spieler nach dem ersten mehr Lebenskraft und schlagen härter zu (Leicht +25 % Lebenskraft / +12,5 % Schaden, Normal +50 % / +25 %, Stark +100 % / +50 % pro weiterem Spieler). Aus: wie im Original."],
	"Open the port on the router": ["Открыть порт на роутере", "Port am Router öffnen"],
	"Co-op host: asks your router to forward UDP port 27015 to this computer so friends can join over the internet (UPnP, else NAT-PMP / PCP), and shows your external IP address to give them. The forwarding is removed when you stop hosting. Off: forward the port by hand.": ["Для сервера сетевой игры: просит роутер перенаправить UDP-порт 27015 на этот компьютер, чтобы друзья могли подключиться через интернет (UPnP, иначе NAT-PMP / PCP), и показывает ваш внешний IP-адрес для них. Перенаправление снимается, когда сервер закрыт. Выкл.: перенаправьте порт вручную.", "Für den Server im Netzwerkspiel: bittet deinen Router, UDP-Port 27015 an diesen Computer weiterzuleiten, damit Freunde über das Internet beitreten können (UPnP, sonst NAT-PMP / PCP), und zeigt deine externe IP-Adresse an, die du ihnen gibst. Die Weiterleitung wird entfernt, wenn du den Server beendest. Aus: Port von Hand weiterleiten."],
	"co-op (remake)": ["сетевая игра (ремейк)", "Netzwerkspiel (Remake)"],
	"Co-op (remake)…": ["Сетевая игра (ремейк)…", "Netzwerkspiel (Remake)…"],
	"Co-op host settings: full experience for every party member, monsters scaled to the player count, opening the port on the router.": ["Настройки сервера сетевой игры: полный опыт каждому в отряде, сила монстров по числу игроков, открытие порта на роутере.", "Servereinstellungen des Netzwerkspiels: volle Erfahrung für jedes Gruppenmitglied, Monster nach Spielerzahl verstärkt, Port am Router öffnen."],
	"WASD camera controls": ["Управление камерой WASD", "WASD-Kamerasteuerung"],
	"WASD: move camera; Q/E: turn; 9/0/-/=: weapons 1-4; R: Aggressive/Defensive; T: Use/Steal. Other keys stay available. Each layout has its own editable bindings on the key pages. Classic restores your previous keys. Original camera always uses Classic.": ["WASD: сдвиг камеры; Q/E: поворот; 9/0/-/=: оружие 1-4; R: атака/защита; T: взять/украсть/использовать. Остальные команды доступны. Раскладки настраиваются отдельно на страницах клавиш. Классическая возвращает прежние клавиши. Оригинальная камера всегда использует её.", "WASD: Kamera bewegen; Q/E: drehen; 9/0/-/=: Waffen 1-4; R: aggressiv/defensiv; T: Nehmen/Stehlen. Andere Befehle bleiben erreichbar. Jede Belegung hat eigene änderbare Tasten. Klassisch stellt die bisherigen Tasten wieder her. Die Originalkamera nutzt immer Klassisch."],
	"Turn camera left": ["Повернуть камеру влево", "Kamera nach links drehen"],
	"Modern camera: turns the camera (Divinity: Original Sin 2 uses Delete).": ["Современная камера: поворачивает камеру (в Divinity: Original Sin 2 — Delete).", "Moderne Kamera: dreht die Kamera (Divinity: Original Sin 2 nutzt Entf)."],
	"Turn camera right": ["Повернуть камеру вправо", "Kamera nach rechts drehen"],
	"Modern camera: turns the camera (Divinity: Original Sin 2 uses End).": ["Современная камера: поворачивает камеру (в Divinity: Original Sin 2 — End).", "Moderne Kamera: dreht die Kamera (Divinity: Original Sin 2 nutzt Ende)."],
	# options_panel.gd
	"More effects…": ["Ещё эффекты…", "Weitere Effekte…"],
	"HD textures, soft and lit particles, contact shadows, torch glow; anti-aliasing, shadow quality, texture filtering.": ["HD-текстуры, мягкие и освещённые частицы, контактные тени, свечение факелов; сглаживание, качество теней, фильтрация текстур.", "HD-Texturen, weiche und beleuchtete Partikel, Kontaktschatten, Fackelleuchten; Kantenglättung, Schattenqualität, Texturfilterung."],
	"Remake options: graphics…": ["Настройки ремейка: графика…", "Remake-Optionen: Grafik…"],
	"The remake's own graphics switches (sky, water, fog, bloom…).": ["Собственные графические настройки ремейка (небо, вода, туман, ореолы…).", "Die eigenen Grafikschalter des Remakes (Himmel, Wasser, Nebel, Bloom…)."],
	"Original look: all effects off": ["Как в оригинале: все эффекты выкл.", "Originaler Look: alle Effekte aus"],
	"Switches every remake graphics effect on both remake pages off, leaving the original 2000 look (confirm with ✓).": ["Выключает все графические эффекты ремейка на обеих его страницах — остаётся вид оригинала 2000 года (подтвердите ✓).", "Schaltet alle Grafikeffekte des Remakes auf beiden Remake-Seiten aus und lässt den originalen Look von 2000 (mit ✓ bestätigen)."],
	"%s\nThe remake's own settings; not part of the original game.": ["%s\nСобственные настройки ремейка; в оригинальной игре их нет.", "%s\nEigene Einstellungen des Remakes; nicht Teil des Originalspiels."],
	"%s\n%s\n(Remake option.)": ["%s\n%s\n(Настройка ремейка.)", "%s\n%s\n(Remake-Option.)"],
	# --- network screen (network_panel.gd), main_menu.gd ---
	"Select «New server» and press ✓ to host": ["Выберите «Новый сервер» и нажмите ✓, чтобы создать игру", "«Neuer Server» wählen und ✓ drücken, um ein Spiel zu eröffnen"],
	" (IP, IP:port or [IPv6]:port) and press ✓ to join": [" (IP, IP:порт или [IPv6]:порт) и нажмите ✓, чтобы присоединиться", " (IP, IP:Port oder [IPv6]:Port) und ✓ drücken, um beizutreten"],
	"Hosting — %d player(s) connected, press ✓ to start": ["Сервер открыт — подключено игроков: %d, нажмите ✓ для начала", "Server offen — %d Spieler verbunden, ✓ startet"],
	"Waiting for the host to start": ["Ожидание начала игры на сервере", "Warten, bis der Server das Spiel startet"],
	"Your LAN address: %s": ["Ваш адрес в локальной сети: %s", "Deine LAN-Adresse: %s"],
	"Internet address (%s): %s": ["Адрес в интернете (%s): %s", "Internetadresse (%s): %s"],
	"IPv6 address: %s": ["Адрес IPv6: %s", "IPv6-Adresse: %s"],
	"copy": ["копировать", "kopieren"],
	"Copied to the clipboard.": ["Скопировано в буфер обмена.", "In die Zwischenablage kopiert."],
	"Now: host a co-op game.": ["Сейчас: создать сетевую игру.", "Jetzt: ein Netzwerkspiel eröffnen."],
	"Now: start the campaign with the players connected.": ["Сейчас: начать кампанию с подключёнными игроками.", "Jetzt: die Kampagne mit den verbundenen Spielern beginnen."],
	"Now: join %s.": ["Сейчас: присоединиться к %s.", "Jetzt: %s beitreten."],
	"Now: nothing — waiting for the host to start.": ["Сейчас: ничего — ожидание начала игры на сервере.", "Jetzt: nichts — warten, bis der Server startet."],
	"Copy this address to the clipboard (remake).": ["Скопировать этот адрес в буфер обмена (ремейк).", "Diese Adresse in die Zwischenablage kopieren (Remake)."],
	# Fallbacks of textslmp.res "string lmp_connection_<n>": the German one has
	# only 0..9 (the original would show the ids), the Russian one all.
	"Refresh": ["Список", "Aktualisieren"],
	"Add/Remove": ["Добавить/Удалить", "Hinzufügen/Entfernen"],
	"Name": ["Имя", "Name"],
	"Island": ["База", "Insel"],
	"Ping": ["Пинг", "Ping"],
	"Enter Server IP address": ["Введите IP-адрес сервера", "Server-IP-Adresse eingeben"],
	" port:": [" порт:", " Port:"],
	"Hero (remake): ": ["Герой (ремейк): ", "Held (Remake): "],
	"Full XP for all: ": ["Полный опыт всем: ", "Volle Erfahrung: "],
	"Scale monsters: ": ["Сила монстров: ", "Monster stärker: "],
	"Bring: ": ["Взять: ", "Mitbringen: "],
	"co-op hero (nothing kept)": ["сетевой герой (без сохранения)", "Netzwerkheld (nichts bleibt)"],
	"new Zak (start fresh)": ["новый Зак (с начала)", "neuer Kiran (Neubeginn)"],
	"Zak of \"%s\"": ["Зак из «%s»", "Kiran aus „%s“"],
	"(Remake: no master server; re-reads the lobby.)": ["(Ремейк: главного сервера нет; обновляет список игроков.)", "(Remake: kein Master-Server; liest die Spielerliste neu.)"],
	"Co-op hero (remake)\nThe hero you play when you join someone's campaign (the host plays Zak). Click to change.": ["Сетевой герой (ремейк)\nГерой, которым вы играете, присоединившись к чужой кампании (на сервере играют за Зака). Щёлкните, чтобы сменить.", "Netzwerkheld (Remake)\nDer Held, den du spielst, wenn du der Kampagne eines anderen beitrittst (der Server spielt Kiran). Zum Ändern klicken."],
	"Full experience for every party member (remake, host)\n%s\nClick to change; also in Options, Game.": ["Полный опыт каждому в команде (ремейк, сервер)\n%s\nЩёлкните, чтобы сменить; также в Настройках, «Игровые».", "Volle Erfahrung für jeden in der Gruppe (Remake, Server)\n%s\nZum Ändern klicken; auch unter Optionen, Spiel."],
	"Scale monsters to player count (remake, host)\n%s\nClick to change; also in Options, Game.": ["Сила монстров по числу игроков (ремейк, сервер)\n%s\nЩёлкните, чтобы сменить; также в Настройках, «Игровые».", "Monster nach Spielerzahl (Remake, Server)\n%s\nZum Ändern klicken; auch unter Optionen, Spiel."],
	"Your hero (remake)\nBring the Zak of one of your saves (or a new one): you play the host's world, and what you achieve there that your own game has not done yet comes back as a new save \"Co-op: <host>\"; your old save is kept. Click to change.": ["Ваш герой (ремейк)\nВозьмите Зака из одной из своих записей (или нового): вы играете в мире сервера, а то, чего вы там добьётесь и чего ещё нет в вашей игре, вернётся новой записью «Сеть: <сервер>»; старая запись сохраняется. Щёлкните, чтобы сменить.", "Dein Held (Remake)\nBring den Kiran eines deiner Spielstände (oder einen neuen) mit: du spielst in der Welt des Servers, und was du dort erreichst, das dein eigenes Spiel noch nicht hat, kommt als neuer Spielstand „Netzwerk: <Server>“ zurück; dein alter Spielstand bleibt erhalten. Zum Ändern klicken."],
	"Your name in the co-op game.": ["Ваше имя в сетевой игре.", "Dein Name im Netzwerkspiel."],
	"Server IP address (port %d).": ["IP-адрес сервера (порт %d).", "IP-Adresse des Servers (Port %d)."],
	"Max players": ["Макс. количество игроков", "Max. Spielerzahl"],
	"Evil Islands": ["Проклятые земли", "Evil Islands"],
	"Your name": ["Ваше имя", "Dein Name"],
	"Co-op hero: ": ["Сетевой герой: ", "Netzwerkheld: "],
	"The hero you play when you join someone's campaign (the host plays Zak).": ["Герой, которым вы играете, присоединившись к чужой кампании (на сервере играют за Зака).", "Der Held, den du spielst, wenn du der Kampagne eines anderen beitrittst (der Server spielt Kiran)."],
	"New campaign (single player)": ["Новая кампания (одиночная игра)", "Neue Kampagne (Einzelspieler)"],
	"Continue (last save)": ["Продолжить (последняя запись)", "Fortsetzen (letzter Spielstand)"],
	"Options": ["Настройки", "Optionen"],
	"Credits": ["Авторы", "Mitwirkende"],
	"Host co-op campaign": ["Создать сетевую кампанию", "Netzwerk-Kampagne eröffnen"],
	"Join": ["Присоединиться", "Beitreten"],
	"Start co-op campaign": ["Начать сетевую кампанию", "Netzwerk-Kampagne starten"],
	"Could not host on port %d (error %d).": ["Не удалось открыть сервер на порту %d (ошибка %d).", "Server auf Port %d konnte nicht eröffnet werden (Fehler %d)."],
	"Hosting on port %d. Waiting for players... (✓ starts)": ["Сервер на порту %d. Ожидание игроков... (✓ — начать)", "Server auf Port %d. Warten auf Spieler... (✓ startet)"],
	"Could not connect (error %d).": ["Не удалось соединиться (ошибка %d).", "Verbindung fehlgeschlagen (Fehler %d)."],
	"Connecting to %s... the host starts the campaign.": ["Соединение с %s... кампанию начинает сервер.", "Verbinde mit %s... der Server startet die Kampagne."],
	"Hosting on port %d.": ["Сервер на порту %d.", "Server auf Port %d."],
	"Connecting to %s...": ["Соединение с %s...", "Verbinde mit %s..."],
	"Connected to %s.": ["Соединено с %s.", "Verbunden mit %s."],
	"host": ["сервер", "Server"],
	"you": ["вы", "Sie"],
	"The host's Evil Islands maps differ from yours: another edition of the game. Both players need an edition with the same maps (the English and Russian ones have them; the German one does not).": ["Карты «Проклятых земель» у сервера не такие, как у вас: другое издание игры. Нужны издания с одинаковыми картами (у английского и русского они одни и те же, у немецкого другие).", "Die Karten von Evil Islands auf dem Server unterscheiden sich von Ihren: eine andere Ausgabe des Spiels. Beide Spieler brauchen eine Ausgabe mit denselben Karten (die englische und die russische haben sie, die deutsche nicht)."],
	# --- UPnP (upnp_port.gd), net status, co-op messages ---
	"UPnP: looking for the router…": ["UPnP: поиск роутера…", "UPnP: Router wird gesucht…"],
	"UPnP: no router answered (%s). Forward UDP port %d by hand to play over the internet.": ["UPnP: роутер не ответил (%s). Чтобы играть через интернет, перенаправьте UDP-порт %d вручную.", "UPnP: kein Router hat geantwortet (%s). Leite UDP-Port %d von Hand weiter, um über das Internet zu spielen."],
	"UPnP: no router with port forwarding found. Forward UDP port %d by hand.": ["UPnP: роутер с перенаправлением портов не найден. Перенаправьте UDP-порт %d вручную.", "UPnP: kein Router mit Portweiterleitung gefunden. Leite UDP-Port %d von Hand weiter."],
	"UPnP: the router refused to open UDP port %d (%s). Forward it by hand.": ["UPnP: роутер отказался открыть UDP-порт %d (%s). Перенаправьте его вручную.", "UPnP: der Router hat das Öffnen von UDP-Port %d abgelehnt (%s). Leite ihn von Hand weiter."],
	"UPnP: UDP port %d is open. Your address for friends: %s": ["UPnP: UDP-порт %d открыт. Ваш адрес для друзей: %s", "UPnP: UDP-Port %d ist offen. Deine Adresse für Freunde: %s"],
	"no router answered (%s)": ["роутер не ответил (%s)", "kein Router hat geantwortet (%s)"],
	"no router with port forwarding": ["нет роутера с перенаправлением портов", "kein Router mit Portweiterleitung"],
	"the router refused (%s)": ["роутер отказал (%s)", "der Router hat abgelehnt (%s)"],
	"%s: UDP port %d is open. Your address for friends: %s": ["%s: UDP-порт %d открыт. Ваш адрес для друзей: %s", "%s: UDP-Port %d ist offen. Deine Adresse für Freunde: %s"],
	"The router opened no port (UPnP: %s; NAT-PMP/PCP: %s). Forward UDP port %d by hand to play over the internet.": ["Роутер не открыл порт (UPnP: %s; NAT-PMP/PCP: %s). Чтобы играть через интернет, перенаправьте UDP-порт %d вручную.", "Der Router hat keinen Port geöffnet (UPnP: %s; NAT-PMP/PCP: %s). Leite UDP-Port %d von Hand weiter, um über das Internet zu spielen."],
	"no answer from %s": ["нет ответа от %s", "keine Antwort von %s"],
	"PCP error %d": ["ошибка PCP %d", "PCP-Fehler %d"],
	"NAT-PMP error %d": ["ошибка NAT-PMP %d", "NAT-PMP-Fehler %d"],
	"(unknown)": ["(неизвестен)", "(unbekannt)"],
	"no gateway": ["нет шлюза", "kein Gateway"],
	"no devices": ["нет устройств", "keine Geräte"],
	"the port is mapped to another computer": ["порт уже перенаправлен на другой компьютер", "der Port ist an einen anderen Computer vergeben"],
	"conflict": ["конфликт", "Konflikt"],
	"not authorised": ["нет прав", "nicht berechtigt"],
	"action failed": ["действие не удалось", "Aktion fehlgeschlagen"],
	"network error": ["ошибка сети", "Netzwerkfehler"],
	"error %d": ["ошибка %d", "Fehler %d"],
	"Connection problems": ["Проблемы со связью", "Verbindungsprobleme"],
	"Save '%s' not found: joining with a co-op hero.": ["Запись «%s» не найдена: вход с сетевым героем.", "Spielstand „%s“ nicht gefunden: Beitritt mit einem Netzwerkhelden."],
	"Co-op: %s": ["Сеть: %s", "Netzwerk: %s"],
	"Co-op progress could not be saved (%d).": ["Не удалось записать успехи сетевой игры (%d).", "Der Fortschritt im Netzwerkspiel konnte nicht gespeichert werden (%d)."],
	"Your progress is saved as \"%s\".": ["Ваши успехи записаны как «%s».", "Dein Fortschritt ist als „%s“ gespeichert."],
	"%s brings their own hero.": ["%s приходит со своим героем.", "%s bringt einen eigenen Helden mit."],
	# --- in game ---
	"Load failed.": ["Не удалось загрузить игру.", "Laden fehlgeschlagen."],
	"Cast %s: click a target (right click cancels)": ["%s: укажите цель (правая кнопка — отмена)", "%s: Ziel anklicken (Rechtsklick bricht ab)"],
	"No quick save.": ["Нет быстрой записи.", "Kein Schnellspeicherstand."],
	"Only the host can save": ["Сохранять игру может только сервер", "Nur der Server kann speichern"],
	"Only the host can save.": ["Сохранять игру может только сервер.", "Nur der Server kann speichern."],
	"Only the host can load": ["Загружать игру может только сервер", "Nur der Server kann laden"],
	"Unknown zone ": ["Неизвестная зона ", "Unbekannte Zone "],
	"Unknown destination ": ["Неизвестная цель перехода ", "Unbekanntes Reiseziel "],
	"Village quests": ["Задания в деревне", "Aufgaben im Dorf"],
	"Close": ["Закрыть", "Schließen"],
	"Finish your current task first.": ["Сначала выполните текущее задание.", "Erfülle zuerst deine aktuelle Aufgabe."],
	"Nobody here needs help right now.": ["Сейчас здесь никому не нужна помощь.", "Hier braucht gerade niemand Hilfe."],
	"%s  (%s, %d experience)\n%s": ["%s  (%s, опыт: %d)\n%s", "%s  (%s, %d Erfahrung)\n%s"],
	"Accept": ["Принять", "Annehmen"],
	"Journal": ["Журнал", "Tagebuch"],
	"Completed": ["Выполнено", "Erfüllt"],
	"No quests yet.": ["Заданий пока нет.", "Noch keine Aufgaben."],
	"Stay here": ["Остаться здесь", "Hier bleiben"],
	"The party leader chooses the destination.": ["Цель перехода выбирает лидер команды.", "Der Anführer der Gruppe wählt das Ziel."],
	"Preparing cutscene...": ["Подготовка видеоролика...", "Zwischensequenz wird vorbereitet..."],
	"Preparing cutscene... %d%%": ["Подготовка видеоролика... %d%%", "Zwischensequenz wird vorbereitet... %d%%"],
	"Spell: ": ["Заклинание: ", "Zauber: "],
	"Rune: ": ["Руна: ", "Rune: "],
	"Unknown": ["Неизвестно", "Unbekannt"],
	# --- first-run setup (setup_screen.gd, GameData.validate, EIInnoSetup) ---
	"Evil Islands - Remake": ["Проклятые земли — ремейк", "Evil Islands - Remake"],
	"This remake uses the data files of your own copy of Evil Islands (GOG / original CD). Select the game's install folder - the one containing game.exe, res/ and maps/ - or the GOG installer (setup_evil_islands_*.exe) to unpack its files once.": ["Ремейк использует файлы данных вашей собственной копии «Проклятых земель» (GOG / оригинальный диск). Укажите папку, куда установлена игра (в ней game.exe, res/ и maps/), или установщик GOG (setup_evil_islands_*.exe), чтобы один раз распаковать его файлы.", "Dieses Remake verwendet die Dateien deiner eigenen Kopie von Evil Islands (GOG / Original-CD). Wähle den Installationsordner des Spiels (mit game.exe, res/ und maps/) oder den GOG-Installer (setup_evil_islands_*.exe), um seine Dateien einmalig zu entpacken."],
	"/path/to/Evil Islands": ["/путь/к/Evil Islands", "/Pfad/zu/Evil Islands"],
	"Browse...": ["Обзор...", "Durchsuchen..."],
	"Use this folder": ["Использовать эту папку", "Diesen Ordner verwenden"],
	"- or -": ["- или -", "- oder -"],
	"/path/to/setup_evil_islands_2.0.0.5.exe": ["/путь/к/setup_evil_islands_2.0.0.5.exe", "/Pfad/zu/setup_evil_islands_2.0.0.5.exe"],
	"Import from installer": ["Распаковать из установщика", "Aus dem Installer entpacken"],
	"Installer": ["Установщик", "Installer"],
	"Unpacking %d files into %s ... (a few minutes, once)": ["Распаковка файлов (%d) в %s ... (несколько минут, один раз)", "Entpacke %d Dateien nach %s ... (einige Minuten, einmalig)"],
	"Folder does not exist.": ["Папка не существует.", "Der Ordner existiert nicht."],
	"Missing %s - point this at the Evil Islands install folder (the one containing game.exe).": ["Нет %s — укажите папку, куда установлены «Проклятые земли» (ту, где лежит game.exe).", "%s fehlt - wähle den Installationsordner von Evil Islands (den mit game.exe)."],
	"Could not read the game archives in res/.": ["Не удалось прочитать архивы игры в res/.", "Die Spielarchive in res/ konnten nicht gelesen werden."],
	"Cannot open the installer.": ["Не удаётся открыть установщик.", "Der Installer kann nicht geöffnet werden."],
	"Not an Inno Setup installer (no offset table).": ["Это не установщик Inno Setup (нет таблицы смещений).", "Kein Inno-Setup-Installer (keine Offset-Tabelle)."],
	"Unsupported installer loader.": ["Неподдерживаемый загрузчик установщика.", "Nicht unterstützter Installer-Loader."],
	"Unsupported installer version: %s": ["Неподдерживаемая версия установщика: %s", "Nicht unterstützte Installer-Version: %s"],
	"Could not read the installer header.": ["Не удалось прочитать заголовок установщика.", "Der Kopf des Installers konnte nicht gelesen werden."],
	"No game files found in the installer.": ["В установщике нет файлов игры.", "Im Installer wurden keine Spieldateien gefunden."],
	"The installer does not contain %s.": ["В установщике нет %s.", "Der Installer enthält %s nicht."],
	"Bad data chunk %d in the installer.": ["Повреждённый блок данных %d в установщике.", "Fehlerhafter Datenblock %d im Installer."],
	"Checksum mismatch in the installer (chunk %d).": ["Неверная контрольная сумма в установщике (блок %d).", "Prüfsummenfehler im Installer (Block %d)."],
	"Cannot write %s.": ["Не удаётся записать %s.", "%s kann nicht geschrieben werden."],
	# --- Inventory panel (B, remake only); terms of the edition's texts.res (camphelp 22, perk mana / health, string attack …) ---
	"Inventory": ["Обоз", "Inventar"],
	"Party bag": ["Общий обоз", "Gruppeninventar"],
	"Gold: %d   ": ["Деньги: %d   ", "Geld: %d   "],
	"%s\nHealth %d/%d   Stamina %d/%d\nStr %d  Dex %d  Int %d\nAttack %d  Defense %d\nDamage %.0f-%.0f   Armor %.1f\nLoad %d/%d\nExperience %d (free %d)": ["%s\nЗдоровье %d/%d   Запас сил %d/%d\nСил %d  Лов %d  Раз %d\nАтака %d  Защита %d\nУрон %.0f-%.0f   Броня %.1f\nВес %d/%d\nОпыт %d (свободно %d)", "%s\nLebenskraft %d/%d   Energie %d/%d\nStä %d  Ges %d  Int %d\nAngriff %d  Verteidigung %d\nSchaden %.0f-%.0f   Rüstung %.1f\nLast %d/%d\nErfahrung %d (frei %d)"],
	"Spells: ": ["Заклинания: ", "Zaubersprüche: "],
	"Abilities: ": ["Навыки: ", "Fähigkeiten: "],
	"Learn an ability...": ["Изучить навык...", "Fähigkeit erlernen..."],
	"%s  (%d exp)": ["%s  (%d опыта)", "%s  (%d Erfahrung)"],
	"Shop": ["Лавка", "Laden"],
	"%s  -  %d gold": ["%s  -  %d монет", "%s  -  %d Gold"],
	"Equipped / belt": ["Надето / пояс", "Ausgerüstet / Gürtel"],
	"[belt] %s": ["[пояс] %s", "[Gürtel] %s"],
	"Equip": ["Надеть", "Ausrüsten"],
	"Put on belt": ["На пояс", "An den Gürtel"],
	"Take off belt": ["Снять с пояса", "Vom Gürtel nehmen"],
	"Learn": ["Изучить", "Erlernen"],
	"Into %s": ["В %s", "In %s"],
	"%s on %s": ["%s на %s", "%s auf %s"],
	"Sell (%d)": ["Продать (%d)", "Verkaufen (%d)"],
	"Repair (%d)": ["Ремонт (%d)", "Reparieren (%d)"],
	"Deconstruct (%d)": ["Разобрать (%d)", "Zerlegen (%d)"],
	"Use": ["Использовать", "Benutzen"],
	"Unequip": ["Снять", "Ablegen"],
	"Buy (%d)": ["Купить (%d)", "Kaufen (%d)"],
	"Build with %s (%d)": ["Собрать из %s (%d)", "Bauen mit %s (%d)"],
	"Map viewer": ["Просмотр карт", "Kartenbetrachter"],
	"Map viewer (remake)": ["Просмотр карт (ремейк)", "Kartenbetrachter (Remake)"],
	# --- Mobile, browser, touch and local save backups ---
	"Skip": ["Пропустить", "Überspringen"],
	"Aim at a body part": ["Удар по части тела", "Körperteil anvisieren"],
	"Head": ["Голова", "Kopf"],
	"Body": ["Тело", "Rumpf"],
	"L arm": ["Л. рука", "L. Arm"],
	"R arm": ["П. рука", "R. Arm"],
	"L leg": ["Л. нога", "L. Bein"],
	"R leg": ["П. нога", "R. Bein"],
	"Menu": ["Меню", "Menü"],
	"Select all": ["Выбрать всех", "Alle wählen"],
	"Centre": ["К герою", "Zentrieren"],
	"Cancel action": ["Отмена", "Abbrechen"],
	"Force move": ["Идти", "Gehen"],
	"Force attack": ["Атаковать", "Angreifen"],
	"Side quests": ["Поручения", "Nebenquests"],
	"Chat": ["Чат", "Chat"],
	"Player name": ["Имя игрока", "Spielername"],
	"Server address": ["Адрес сервера", "Serveradresse"],
	"Save name": ["Имя сохранения", "Spielstandname"],
	"Export saves": ["Экспорт сохранений", "Spielstände exportieren"],
	"Import saves": ["Импорт сохранений", "Spielstände importieren"],
	"Cursed Lands saves": ["Сохранения Cursed Lands", "Cursed-Lands-Spielstände"],
	"Save backup is too large.": ["Резервная копия сохранений слишком велика.", "Die Sicherung der Spielstände ist zu groß."],
	"This is not a Cursed Lands save backup.": ["Это не резервная копия сохранений Cursed Lands.", "Dies ist keine Spielstandsicherung von Cursed Lands."],
	"Too many saves in the backup.": ["В резервной копии слишком много сохранений.", "Die Sicherung enthält zu viele Spielstände."],
	"Invalid file in the save backup.": ["Недопустимый файл в резервной копии.", "Ungültige Datei in der Spielstandsicherung."],
	"Damaged save backup.": ["Резервная копия повреждена.", "Die Spielstandsicherung ist beschädigt."],
	"These saves were just imported. Try again in a moment.": ["Эти сохранения только что импортированы. Повторите чуть позже.", "Diese Spielstände wurden gerade importiert. Bitte kurz warten und erneut versuchen."],
	"Could not write saves. Check free storage.": ["Не удалось записать сохранения. Проверьте свободное место.", "Spielstände konnten nicht gespeichert werden. Bitte freien Speicher prüfen."],
	"%d saves imported into new slots.": ["Сохранений импортировано в новые ячейки: %d.", "%d Spielstände in neue Plätze importiert."],
	"Saves exported.": ["Сохранения экспортированы.", "Spielstände exportiert."],
	"Could not export saves.": ["Не удалось экспортировать сохранения.", "Spielstände konnten nicht exportiert werden."],
	"Could not open the chosen document.": ["Не удалось открыть выбранный документ.", "Das gewählte Dokument konnte nicht geöffnet werden."],
	"The backup cannot be read or is too large.": ["Не удалось прочитать резервную копию, либо она слишком велика.", "Die Sicherung ist nicht lesbar oder zu groß."],
	"Import the data from your own copy of Evil Islands. Your files stay on this device.": ["Импортируйте данные из своей копии «Проклятых земель». Файлы останутся на этом устройстве.", "Importiere die Daten deiner eigenen Kopie von Evil Islands. Deine Dateien bleiben auf diesem Gerät."],
	"Choose your GOG installer (setup_evil_islands_*.exe): the browser unpacks it without running it. The installed game folder or a private .eipack also work.": ["Выберите установщик GOG (setup_evil_islands_*.exe): браузер распакует его без запуска. Подойдёт и папка установленной игры или личный файл .eipack.", "Wähle deinen GOG-Installer (setup_evil_islands_*.exe): Der Browser entpackt ihn, ohne ihn auszuführen. Der Ordner des installierten Spiels oder eine private .eipack-Datei gehen auch."],
	# Messages of the browser import (web/files.js, web/installer-worker.js).
	"Checking your local game files…": ["Проверка файлов игры…", "Spieldateien werden geprüft…"],
	"Reading the installer…": ["Чтение установщика…", "Installer wird gelesen…"],
	"Saving your data pack on this device…": ["Сохранение пакета данных на этом устройстве…", "Datenpaket wird auf diesem Gerät gespeichert…"],
	"Game data imported.": ["Данные игры импортированы.", "Spieldaten importiert."],
	"Game data imported. Export saves regularly; browser storage may be cleared.": ["Данные игры импортированы. Регулярно экспортируйте сохранения: браузер может очистить хранилище.", "Spieldaten importiert. Exportiere Spielstände regelmäßig; der Browser kann seinen Speicher leeren."],
	"Not enough browser storage for this import. Free space and try again.": ["Недостаточно места в хранилище браузера. Освободите место и повторите.", "Nicht genug Browserspeicher für diesen Import. Gib Speicher frei und versuche es erneut."],
	"Browser storage is full. Free space and try again.": ["Хранилище браузера заполнено. Освободите место и повторите.", "Der Browserspeicher ist voll. Gib Speicher frei und versuche es erneut."],
	"The installer could not be unpacked: %s": ["Не удалось распаковать установщик: %s", "Der Installer konnte nicht entpackt werden: %s"],
	"Choose the GOG installer (.exe), a data pack (.eipack) or the game folder.": ["Выберите установщик GOG (.exe), пакет данных (.eipack) или папку игры.", "Wähle den GOG-Installer (.exe), ein Datenpaket (.eipack) oder den Spielordner."],
	"Choose your GOG installer (.exe) or a private .eipack. The installer is unpacked without running it.": ["Выберите установщик GOG (.exe) или личный файл .eipack. Установщик будет распакован без запуска.", "Wähle deinen GOG-Installer (.exe) oder eine private .eipack-Datei. Der Installer wird entpackt, ohne ihn auszuführen."],
	"Evil Islands installer or data pack": ["Установщик или данные «Проклятых земель»", "Evil-Islands-Installer oder Datenpaket"],
	"Choose data pack…": ["Выбрать пакет данных…", "Datenpaket wählen…"],
	"Choose game folder…": ["Выбрать папку игры…", "Spielordner wählen…"],
	"Choose installer / data pack…": ["Выбрать установщик / пакет данных…", "Installer / Datenpaket wählen…"],
	"Cancel import": ["Отменить импорт", "Import abbrechen"],
	"Save storage is unavailable. Allow browser storage before playing.": ["Хранилище сохранений недоступно. Разрешите хранение данных в браузере перед игрой.", "Der Spielstandspeicher ist nicht verfügbar. Erlaube die Datenspeicherung im Browser, bevor du spielst."],
	"Opening game data…": ["Открытие данных игры…", "Spieldaten werden geöffnet…"],
	"Copying installer: %d%%": ["Копирование установщика: %d%%", "Installer wird kopiert: %d%%"],
	"Unpacking installer: %d%%": ["Распаковка установщика: %d%%", "Installer wird entpackt: %d%%"],
	"Importing %s": ["Импорт: %s", "Import: %s"],
	"The selected document could not be opened.": ["Не удалось открыть выбранный документ.", "Das gewählte Dokument konnte nicht geöffnet werden."],
	"Could not create the private import folder.": ["Не удалось создать папку импорта приложения.", "Der private Importordner konnte nicht erstellt werden."],
	"Could not read the selected installer.": ["Не удалось прочитать выбранный установщик.", "Der gewählte Installer konnte nicht gelesen werden."],
	"Not enough space to copy the installer.": ["Недостаточно места для копирования установщика.", "Nicht genug Speicher zum Kopieren des Installers."],
	"Import cancelled.": ["Импорт отменён.", "Import abgebrochen."],
	"Invalid data pack header.": ["Недопустимый заголовок пакета данных.", "Ungültiger Datenpaketkopf."],
	"Invalid data pack index.": ["Недопустимый индекс пакета данных.", "Ungültiger Datenpaketindex."],
	"Invalid data pack entry.": ["Недопустимая запись в пакете данных.", "Ungültiger Datenpaketeintrag."],
	"Invalid data pack path.": ["Недопустимый путь в пакете данных.", "Ungültiger Pfad im Datenpaket."],
	"Invalid data pack range.": ["Недопустимый диапазон в пакете данных.", "Ungültiger Datenbereich im Datenpaket."],
	"Could not write imported game data.": ["Не удалось записать импортируемые данные игры.", "Importierte Spieldaten konnten nicht geschrieben werden."],
	"The data pack is incomplete.": ["Пакет данных неполон.", "Das Datenpaket ist unvollständig."],
	"Not enough space to import game data.": ["Недостаточно места для импорта данных игры.", "Nicht genug Speicher zum Importieren der Spieldaten."],
	"WebSocket: ": ["WebSocket: ", "WebSocket: "],
	"WebSocket host: ": ["Сервер WebSocket: ", "WebSocket-Host: "],
	"Join a WebSocket host with wss:// (ws:// on localhost). Hosting runs on desktop or Android.": ["Адрес сервера WebSocket: wss:// (ws:// для localhost). Сервер запускается на ПК или Android.", "WebSocket-Host mit wss:// beitreten (ws:// auf localhost). Hosten ist auf PC oder Android möglich."],
	"Browser players join a desktop or Android WebSocket host.": ["Игроки в браузере подключаются к серверу WebSocket на ПК или Android.", "Browser-Spieler treten einem WebSocket-Host auf PC oder Android bei."],

}
