extends RefCounted
## Full soft-sand slots only; altered/unknown atlases stay unclassified.
## Generated by tools/benchmarks/biome_sand_metadata.py from renderer
## 0092dc6e1d7c4aab3f74644a79e9bfca11ecf293 Source/terrain_tile_presets.h.
## That table credits ei-mapper-endurance af24d45 editor family metadata.
## Fingerprints: original 512x512 RGBA8 pixels without mipmaps.
const IDENTITIES := {
	# Zone15:0
	"0552d0b39a33859bdf869250ff0f9a029005518c34aee23872272c49bc79cb22": [5, 10, 11],
	# Zone15:7
	"196441769cc7a3d699ff7378f32a17a3e31fafe438a9f955e210a1f127f937be": [2, 11, 15, 20, 26, 40],
	# Zone19:4
	"1ee62a701b04bcbb4c68dc9ab03648aa6629fa73207819e72bc470b9509dcd19": [42, 43, 44, 45, 46, 47, 62, 63],
	# bz16h:0
	"20d7e1357aebdcf6102d7ed9653e81f37ba1f1c6b363161d14168df4b8347990": [0, 3, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63],
	# bz13h:6
	"457b8e4059db6c39163a4ca2994a3ef2063a2c1c98f9d02a4a6e2faeb42a20cc": [11, 12, 34, 35, 36, 40, 60, 61],
	# bz13h:5
	"45b089b1d990705542cdd5a00ef12c0c131f5d800ede0b46f914c084d7f73e26": [0, 1, 2],
	# bz16h:4
	"516a61fc0d82c61fa76e4693035b32b09c265185bcb091cc7dc168ee934beba4": [28, 29, 30, 31, 32, 33],
	# Zone15:6
	"534ed90fbba676e6bf108a56649413f8caefb493ce22025a08c79c59fbd5dfec": [11, 12, 34, 35, 36, 40, 60, 61],
	# bz13h:2
	"63ad6ac482e5820bbca237abb5966ce84ee3d3c3088e63ee65af5242025de196": [39, 40, 41, 42, 43, 44, 45],
	# Zone19:0
	"891da2b2c45a5b484e3ea9b5028fca0ec6fd6e0a1d2b7d7c106b26ec1f995657": [0, 3, 6, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63],
	# bz13h:0
	"8a7e9903945d53a4651e64c3d98410be9fc2b9ab891b2bfe31a0615b93b88639": [5, 10, 11],
	# Zone15:5
	"8c7b74ce7f4498c0fc532be1dbd8e93e3fe59ffd6d40cc55c495e5fd58d5d453": [0, 1, 2],
	# Zone19:1
	"95b8c155a2dd5b46b462966d6a4734f312e57fff33939a9954f5b32e8deaa406": [18, 19, 20, 21, 22, 23, 24, 25, 26, 36, 37, 38, 39, 40, 41, 42, 43, 44, 63],
	# bz13h:1
	"9af561ce2759c63be41ed34046b3a1b97d9854cec59356fafa07b3b6091b58c5": [9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53],
	# Zone13:0
	"9c3da28173773cf30ccdf4cca73ac3ab65fdd063ed7f8bb96f8cf6ca46fb2b93": [60],
	# Zone19:2
	"9dc4455bc17351a5e75d6fc5a19b36a7005554e403dd04d7cb903f3fdcffaee3": [0, 1, 2, 3, 4, 5, 6, 16, 17, 18, 19, 20, 21, 22, 23, 24],
	# Zone15:1
	"9eb63276636cd908eb1f5dadd9b533f29c88d89a77ebaff90318b111b5060242": [9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53],
	# Zone18:4
	"a13aa7c650a2010eed1ad37c669b49aae481c2e30bbea052481567538a70366a": [28, 29, 30, 31, 32, 33],
	# Zone18:0
	"bde110e65a114a35aa72f43d85a5b4506d7b30aaff6a6f345fd133f3ffd2a2c7": [0, 3, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63],
	# bz13h:4
	"cae209e84a6991f0d2a765d020caaea55ab2e2929cce575a5da89a7a8f26675d": [49, 50, 51, 52, 53, 54, 55, 56],
	# Zone15:2
	"d6f73b0b2ab88d8f5077945123cd9efefe556cb0c8acea0596d0a822ac2f4beb": [39, 40, 41, 42, 43, 44, 45],
	# Zone19:7
	"dbf30f0e4c71f518a69afd15a8d901b7ff5fea065712906f0a60972d2a86a7cf": [5, 6, 23, 24, 26, 36, 38, 47],
	# Zone19:5
	"dd473883358471f469bfe21b1aa0950ff317024aec2ac8512d2a541cbf43c4ce": [0, 1, 32, 33, 34],
	# bz16h:1, Zone18:1
	"eb8f47229b8e187cef9d138b41d608a640c65c5343fa89c090bc345f07075fc5": [0, 1, 2, 3, 4, 5, 6, 37, 38, 39, 40, 41, 42, 43, 44, 45],
	# Zone19:6
	"ee4ea5b5eea8dfa908f1ab620643a61bcb7a6dda7ef1d69351f6d24cc5c0d4e0": [26, 38, 39, 55, 62],
	# Zone15:4
	"f2414a92c2f05ee0dfebcd6c9a83af4259acb5879d6ec4bdb2b93cabf6d46690": [49, 50, 51, 52, 53, 54, 55, 56],
	# bz13h:7
	"f943f12061785c548d876824b99a55409db1e3ef713fa78d760a03712f905502": [2, 11, 15, 20, 26, 40],
}


static func slots(image: Image) -> Array:
	if image==null or image.get_size()!=Vector2i(512,512): return []
	var pixels := image
	if image.is_compressed() or image.get_format()!=Image.FORMAT_RGBA8 or image.has_mipmaps():
		pixels = image.duplicate() as Image
		if pixels.is_compressed(): pixels.decompress()
		pixels.clear_mipmaps(); pixels.convert(Image.FORMAT_RGBA8)
	var digest := HashingContext.new(); digest.start(HashingContext.HASH_SHA256)
	digest.update(pixels.get_data())
	return IDENTITIES.get(digest.finish().hex_encode(),[])
